version: '3.8'

services:
    app:
        image: php:8.1-fpm
        container_name: newsaggregator_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
        command: php -S 0.0.0.0:8000 -t public

    db:
        image: mysql:latest
        container_name: newsaggregator_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: news_aggregator_api
            MYSQL_USER: newsAggreagtor
            MYSQL_PASSWORD: newsAggreagtor@123
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:

networks:
    newsaggregator_network:
        driver: bridge
